// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class Drzava
    {
        public Drzava()
        {
            Mjesto = new HashSet<Mjesto>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }

        public virtual ICollection<Mjesto> Mjesto { get; set; }
    }
}