// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class Klijent
    {
        public Klijent()
        {
            Ponuda = new HashSet<Ponuda>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public int PartnerId { get; set; }
        public int PrimarniKontaktId { get; set; }
        public string Napomena { get; set; }
        public string Adresa { get; set; }
        public int MjestoId { get; set; }

        public virtual Mjesto Mjesto { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<Ponuda> Ponuda { get; set; }
    }
}