// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class Mjesto
    {
        public Mjesto()
        {
            Klijent = new HashSet<Klijent>();
            Partner = new HashSet<Partner>();
        }

        public int Id { get; set; }
        public string PostanskiBroj { get; set; }
        public string Naziv { get; set; }
        public int DrzavaId { get; set; }

        public virtual Drzava Drzava { get; set; }
        public virtual ICollection<Klijent> Klijent { get; set; }
        public virtual ICollection<Partner> Partner { get; set; }
    }
}