// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class Ponuda
    {
        public Ponuda()
        {
            StavkaPonude = new HashSet<StavkaPonude>();
            StavkaPopust = new HashSet<StavkaPopust>();
        }

        public int Id { get; set; }
        public string Broj { get; set; }
        public string Status { get; set; }
        public DateTimeOffset StatusDatum { get; set; }
        public DateTimeOffset DatumKreiranja { get; set; }
        public int ValutaPlaćanja { get; set; }
        public DateTimeOffset StartDatum { get; set; }
        public DateTimeOffset EndDatum { get; set; }
        public string Oib { get; set; }
        public string Brand { get; set; }
        public bool Izvoz { get; set; }
        public string Valuta { get; set; }
        public string Napomena { get; set; }
        public decimal Ukupno { get; set; }
        public bool Pdv { get; set; }
        public decimal ZaPlatiti { get; set; }
        public int UgovorId { get; set; }
        public int PartnerId { get; set; }
        public int KlijentId { get; set; }

        public virtual Klijent Klijent { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Ugovor Ugovor { get; set; }
        public virtual ICollection<StavkaPonude> StavkaPonude { get; set; }
        public virtual ICollection<StavkaPopust> StavkaPopust { get; set; }
    }
}