// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class StavkaPonude
    {
        public int Id { get; set; }
        public string Opis { get; set; }
        public decimal Količina { get; set; }
        public decimal JedinicnaCijena { get; set; }
        public decimal Cijena { get; set; }
        public decimal Popust { get; set; }
        public decimal Iznos { get; set; }
        public int PonudaId { get; set; }

        public virtual Ponuda Ponuda { get; set; }
    }
}