// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class StavkaPopust
    {
        public int Id { get; set; }
        public decimal AgePopust { get; set; }
        public decimal AgeIznos { get; set; }
        public decimal AvansPopust { get; set; }
        public decimal AvansIznos { get; set; }
        public int PonudaId { get; set; }

        public virtual Ponuda Ponuda { get; set; }
    }
}