// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlugAndPlay.Dal.Model
{
    public partial class User
    {
        public User()
        {
            RefreshToken = new HashSet<RefreshToken>();
            UserRole = new HashSet<UserRole>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<RefreshToken> RefreshToken { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}